// GENERATED by `deno task gen:interface` — do not edit
//
// Building-family data interfaces derived from vocab/building.ttl (properties grouped
// by rdfs:domain) + enum unions from the controlled-vocab instances. Source of truth is
// the .ttl; regenerate with `deno task gen:interface`. A freshness test guards drift.

export type GeocodePrecision = "Address" | "City" | "Postcode";
export type IndoorTemperatureClass = "MaxEighteenDegrees" | "MaxTwelveDegrees";
export type ShiftRegime = "OneShift" | "ThreeShift" | "TwoShift";
export type TenancyType = "MultiTenant" | "SingleTenant";

export interface GeoPointFields {
  geocodePrecision?: GeocodePrecision;
}

export interface BuildingCertificationFields {
  certificationLevel?: string;
  certificationScope?: string;
}

export interface OperatingCostsFields {
  caretaker?: string;
  exteriorMaintenance?: string;
  glassCleaning?: string;
  insurance?: string;
  operationInspectionAndMaintenance?: string;
  propertyManagement?: string;
  repairAndMaintenance?: string;
  routineCleaningOffice?: string;
  routineCleaningWarehouse?: string;
  security?: string;
  wasteDisposal?: string;
}

export interface TechnicalSystemFields {
  capacityKW?: number;
  commissioningYear?: number;
  storageCapacityKWh?: number;
  thermalCapacityKW?: number;
}

export interface BuildingFlatFields {
  customer?: string;
  locality?: string;
  postalCode?: string;
  region?: string;
  streetAddress?: string;
  label?: string;
  buildingArea?: number;
  landArea?: number;
  investor?: string;
  ownedBy?: string;
  operatedBy?: string;
  facilityManagedBy?: string;
  developedBy?: string;
  consultedBy?: string;
  officeArea?: number;
  usedAs?: string;
  yearOfConstruction?: number;
  energyCertificate?: string;
  naceCode?: string;
  buildingCode?: string;
  hallArea?: number;
  officeSocialArea?: number;
  buildingHeight?: number;
  numberOfLoadingDocks?: number;
  yearOfRenovation?: number;
  leaseType?: string;
  tenantIndustry?: string;
  shiftRegime?: ShiftRegime;
  tenancyType?: TenancyType;
  indoorTemperatureClass?: IndoorTemperatureClass;
  logisticsFunction?: string;
  climateControlType?: string;
  greenLeaseShare?: number;
  companyName?: string;
}
