// GENERATED by `deno task gen:interface` — do not edit
//
// Consumption-family data interfaces derived from vocab/consumption.ttl via the
// field bridges in consumptionConfig.ts. Source of truth is the .ttl + that bridge;
// regenerate with `deno task gen:interface`. A freshness test guards drift.

import type { AggregationKind, Scenario } from "../../types.ts";

export interface EnergyDatasetFields {
  granularity: string;
  scenario: Scenario;
}

export interface AggregationDefinitionFields {
  name: string;
  aggregationType: AggregationKind;
  period?: string;
  benchmark?: boolean;
  createdAt: string;
  lastComputedAt?: string;
}

export interface AggregationSnapshotFields {
  name: string;
  aggregationType: AggregationKind;
  computedAt: string;
  buildingCount: number;
  computedBy?: string;
  metricPeriod?: string;
}
