// GENERATED by `deno task gen:schema` — do not edit
//
// Per-property schema parsed from vocab/*.ttl: range, datatype, enum/structured
// classification, functional cardinality, optional canonical unit. Source of truth
// is the .ttl files; regenerate with `deno task gen:schema`. A freshness test guards drift.

export type TermKind = "literal" | "agent" | "enum" | "structured";

export interface TermSchema {
  kind: TermKind;
  datatype?: string;
  range?: string;
  functional: boolean;
  instances?: string[];
  unit?: string;
}

export const VOCAB_SCHEMA: Record<string, TermSchema> =
  {
  "https://solid.ti.rw.fau.de/gra/building.ttl#buildingCode": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#buildingHeight": { kind: "literal", datatype: "decimal", range: "http://www.w3.org/2001/XMLSchema#decimal", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#capacityKW": { kind: "literal", datatype: "decimal", range: "http://www.w3.org/2001/XMLSchema#decimal", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#caretaker": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#certificationLevel": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#certificationScope": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#climateControlType": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#commissioningYear": { kind: "literal", datatype: "gYear", range: "http://www.w3.org/2001/XMLSchema#gYear", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#companyName": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#consultedBy": { kind: "agent", range: "http://xmlns.com/foaf/0.1/Agent", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#developedBy": { kind: "agent", range: "http://xmlns.com/foaf/0.1/Agent", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#exteriorMaintenance": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#facilityManagedBy": { kind: "agent", range: "http://xmlns.com/foaf/0.1/Agent", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#geocodePrecision": { kind: "enum", range: "https://solid.ti.rw.fau.de/gra/building.ttl#GeocodePrecision", functional: false, instances: ["https://solid.ti.rw.fau.de/gra/building.ttl#Address", "https://solid.ti.rw.fau.de/gra/building.ttl#City", "https://solid.ti.rw.fau.de/gra/building.ttl#Postcode"] },
  "https://solid.ti.rw.fau.de/gra/building.ttl#glassCleaning": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#greenLeaseShare": { kind: "literal", datatype: "decimal", range: "http://www.w3.org/2001/XMLSchema#decimal", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#hallArea": { kind: "literal", datatype: "decimal", range: "http://www.w3.org/2001/XMLSchema#decimal", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#hasAttachment": { kind: "structured", range: "http://schema.org/MediaObject", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#hasBuildingArea": { kind: "literal", datatype: "integer", range: "http://www.w3.org/2001/XMLSchema#integer", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#hasBuildingCertification": { kind: "structured", range: "https://solid.ti.rw.fau.de/gra/building.ttl#BuildingCertification", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#hasEnergyCertificate": { kind: "literal", datatype: "string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#hasLandArea": { kind: "literal", datatype: "integer", range: "http://www.w3.org/2001/XMLSchema#integer", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#hasOperatingCosts": { kind: "structured", range: "https://solid.ti.rw.fau.de/gra/building.ttl#OperatingCosts", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#hasSystem": { kind: "structured", range: "https://solid.ti.rw.fau.de/gra/building.ttl#TechnicalSystem", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#indoorTemperatureClass": { kind: "enum", range: "https://solid.ti.rw.fau.de/gra/building.ttl#IndoorTemperatureClass", functional: false, instances: ["https://solid.ti.rw.fau.de/gra/building.ttl#MaxEighteenDegrees", "https://solid.ti.rw.fau.de/gra/building.ttl#MaxTwelveDegrees"] },
  "https://solid.ti.rw.fau.de/gra/building.ttl#insurance": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#investor": { kind: "agent", range: "http://xmlns.com/foaf/0.1/Agent", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#leaseType": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#logisticsFunction": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#numberOfLoadingDocks": { kind: "literal", datatype: "integer", range: "http://www.w3.org/2001/XMLSchema#integer", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#officeArea": { kind: "literal", datatype: "integer", range: "http://www.w3.org/2001/XMLSchema#integer", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#officeSocialArea": { kind: "literal", datatype: "decimal", range: "http://www.w3.org/2001/XMLSchema#decimal", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#operationInspectionAndMaintenance": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#propertyManagement": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#repairAndMaintenance": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#routineCleaningOffice": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#routineCleaningWarehouse": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#security": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#shiftRegime": { kind: "enum", range: "https://solid.ti.rw.fau.de/gra/building.ttl#ShiftRegime", functional: false, instances: ["https://solid.ti.rw.fau.de/gra/building.ttl#OneShift", "https://solid.ti.rw.fau.de/gra/building.ttl#ThreeShift", "https://solid.ti.rw.fau.de/gra/building.ttl#TwoShift"] },
  "https://solid.ti.rw.fau.de/gra/building.ttl#storageCapacityKWh": { kind: "literal", datatype: "decimal", range: "http://www.w3.org/2001/XMLSchema#decimal", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#tenancyType": { kind: "enum", range: "https://solid.ti.rw.fau.de/gra/building.ttl#TenancyType", functional: false, instances: ["https://solid.ti.rw.fau.de/gra/building.ttl#MultiTenant", "https://solid.ti.rw.fau.de/gra/building.ttl#SingleTenant"] },
  "https://solid.ti.rw.fau.de/gra/building.ttl#tenantIndustry": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#thermalCapacityKW": { kind: "literal", datatype: "decimal", range: "http://www.w3.org/2001/XMLSchema#decimal", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#usedAs": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#wasteDisposal": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#yearOfConstruction": { kind: "literal", datatype: "integer", range: "http://www.w3.org/2001/XMLSchema#integer", functional: false },
  "https://solid.ti.rw.fau.de/gra/building.ttl#yearOfRenovation": { kind: "literal", datatype: "integer", range: "http://www.w3.org/2001/XMLSchema#integer", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#ElectricityConsumption": { kind: "literal", datatype: "string", functional: false, unit: "https://qudt.org/vocab/unit#KiloW-HR" },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#ElectricityGeneration": { kind: "literal", datatype: "string", functional: false, unit: "https://qudt.org/vocab/unit#KiloW-HR" },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#HeatConsumption": { kind: "literal", datatype: "string", functional: false, unit: "https://qudt.org/vocab/unit#KiloW-HR" },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#RenewableSelfGeneratedShare": { kind: "literal", datatype: "string", functional: false, unit: "https://qudt.org/vocab/unit#PERCENT" },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#WastewaterConsumption": { kind: "literal", datatype: "string", functional: false, unit: "https://qudt.org/vocab/unit#M3" },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#WaterConsumption": { kind: "literal", datatype: "string", functional: false, unit: "https://qudt.org/vocab/unit#M3" },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#aggregationId": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#aggregationName": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#aggregationPeriod": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#aggregationType": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#benchmark": { kind: "literal", datatype: "boolean", range: "http://www.w3.org/2001/XMLSchema#boolean", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#buildingCount": { kind: "literal", datatype: "integer", range: "http://www.w3.org/2001/XMLSchema#integer", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#canonicalUnit": { kind: "literal", datatype: "string", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#computedAt": { kind: "literal", datatype: "dateTime", range: "http://www.w3.org/2001/XMLSchema#dateTime", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#computedBy": { kind: "agent", range: "http://xmlns.com/foaf/0.1/Agent", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#createdAt": { kind: "literal", datatype: "dateTime", range: "http://www.w3.org/2001/XMLSchema#dateTime", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#datasetLocation": { kind: "structured", range: "http://www.w3.org/2000/01/rdf-schema#Resource", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#extentLevel": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#granularity": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#hasEnergyDataset": { kind: "structured", range: "https://solid.ti.rw.fau.de/gra/consumption.ttl#EnergyDataset", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#includesBuilding": { kind: "structured", range: "https://w3id.org/rec#Building", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#includesMetric": { kind: "literal", datatype: "string", range: "http://www.w3.org/2001/XMLSchema#string", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#lastComputedAt": { kind: "literal", datatype: "dateTime", range: "http://www.w3.org/2001/XMLSchema#dateTime", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#metricPeriod": { kind: "literal", datatype: "gYear", range: "http://www.w3.org/2001/XMLSchema#gYear", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#ofBuilding": { kind: "structured", range: "https://w3id.org/rec#Building", functional: false },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#scenario": { kind: "enum", range: "https://solid.ti.rw.fau.de/gra/consumption.ttl#Scenario", functional: false, instances: ["https://solid.ti.rw.fau.de/gra/consumption.ttl#Actual", "https://solid.ti.rw.fau.de/gra/consumption.ttl#Planned"] },
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#spatialExtent": { kind: "structured", range: "http://www.w3.org/2004/02/skos/core#Concept", functional: false },
  "https://solid.ti.rw.fau.de/gra/vocab.ttl#currentRoom": { kind: "literal", datatype: "string", functional: false },
  "https://solid.ti.rw.fau.de/gra/vocab.ttl#demoSeedDeclined": { kind: "literal", datatype: "boolean", range: "http://www.w3.org/2001/XMLSchema#boolean", functional: false },
  "https://solid.ti.rw.fau.de/gra/vocab.ttl#hiddenBuilding": { kind: "structured", range: "https://w3id.org/rec#Building", functional: false },
  "https://solid.ti.rw.fau.de/gra/vocab.ttl#kind": { kind: "structured", range: "http://www.w3.org/2000/01/rdf-schema#Class", functional: false },
  "https://solid.ti.rw.fau.de/gra/vocab.ttl#knownRoom": { kind: "literal", datatype: "string", functional: false },
  "https://w3id.org/rec#operatedBy": { kind: "agent", range: "http://xmlns.com/foaf/0.1/Agent", functional: false },
  "https://w3id.org/rec#ownedBy": { kind: "agent", range: "http://xmlns.com/foaf/0.1/Agent", functional: false },
};
