/// <reference lib="deno.ns" />
/**
 * Benchmark output: timing helpers + gnuplot data files (`.dat`) + plot scripts
 * (`.gp`) + rendered PNG graphs (for the paper). The benchmark is
 * MEASURE-AND-REPORT — nothing here asserts a time budget; it records numbers and
 * draws them.
 *
 * Split so the formatting is testable offline (Tier 1, `report.test.ts`): the pure
 * functions `formatDat` / `gnuplotScript` build strings; `writeDat` / `writeGp` are
 * the thin disk wrappers; `renderGraphs` shells out to gnuplot ONLY when it's on
 * PATH (graceful — a missing binary prints an install hint, never throws, so a
 * machine without gnuplot still gets the `.dat` + `.gp` to render elsewhere).
 *
 * The plot CATALOG (which `.dat` → which graph) lives in `plots.ts`; this module
 * is the generic formatting/render machinery it builds on.
 */

/** Output directory for all benchmark artifacts (`test/bench/results/`). */
export const RESULTS_DIR = `${import.meta.dirname}/results`;

// ── Timing ────────────────────────────────────────────────────────────────────

/** Median of a numeric array (numeric sort; mean of the two middles when even). */
export function median(xs: number[]): number {
  if (xs.length === 0) return NaN;
  const s = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
}

/**
 * Run `fn` `runs` times and return the MEDIAN wall-clock ms (median shrugs off the
 * odd GC / network blip better than the mean). `runs` defaults to 3; pass 1 for
 * one-shot measurements (e.g. an expensive seed already done once).
 */
export async function measure(fn: () => Promise<unknown>, runs = 3): Promise<number> {
  const samples: number[] = [];
  for (let i = 0; i < runs; i++) {
    const t0 = performance.now();
    await fn();
    samples.push(performance.now() - t0);
  }
  return median(samples);
}

// ── Data files (gnuplot-friendly whitespace columns) ────────────────────────────

type Cell = number | string;

/**
 * Format a whitespace-separated data table with a `#`-commented header line
 * (gnuplot treats `#` lines as comments, so the header is documentation only).
 * Numbers are rounded to 3 decimals; everything is space-padded for readability.
 */
export function formatDat(header: string[], rows: Cell[][]): string {
  const fmt = (c: Cell): string =>
    typeof c === "number" ? (Number.isInteger(c) ? String(c) : c.toFixed(3)) : c;
  const lines = [`# ${header.join("  ")}`];
  for (const row of rows) lines.push(row.map(fmt).join("  "));
  return lines.join("\n") + "\n";
}

export async function writeDat(
  dir: string,
  name: string,
  header: string[],
  rows: Cell[][],
): Promise<string> {
  await Deno.mkdir(dir, { recursive: true });
  const path = `${dir}/${name}.dat`;
  await Deno.writeTextFile(path, formatDat(header, rows));
  return path;
}

// ── gnuplot scripts (pngcairo) ──────────────────────────────────────────────────

/** One plotted curve: which `.dat` column to read and how to label it. */
export interface PlotSeries {
  /** 1-based data column (matches gnuplot's `using` numbering). */
  col: number;
  title: string;
  /** Put this curve on the secondary y2 axis (e.g. the per-item ms/N curve). */
  y2?: boolean;
}

export interface PlotSpec {
  /** Base name (no extension): reads `<name>.dat`, writes `<name>.png`. */
  name: string;
  title: string;
  xlabel: string;
  ylabel: string;
  y2label?: string;
  /** 1-based x column (default 1). */
  xcol?: number;
  series: PlotSeries[];
}

// Filled point types that stay distinguishable in black & white print.
const POINT_TYPES = [7, 5, 9, 13, 11, 4];

/**
 * Build a self-contained gnuplot script (PNG via pngcairo) for one graph. Vector
 * PDF was the obvious choice for print, but the user picked PNG; the distinct
 * filled point types + dashtypes keep curves separable on a B/W page anyway.
 */
export function gnuplotScript(spec: PlotSpec): string {
  const xcol = spec.xcol ?? 1;
  const hasY2 = spec.series.some((s) => s.y2);
  const head = [
    `# Generated by test/bench/report.ts — regenerate with: deno task bench:plot`,
    `set terminal pngcairo size 900,560 font ",12"`,
    `set output "${spec.name}.png"`,
    `set title "${spec.title}"`,
    `set xlabel "${spec.xlabel}"`,
    `set ylabel "${spec.ylabel}"`,
    `set grid`,
    `set key top left`,
  ];
  if (hasY2) {
    head.push(`set y2label "${spec.y2label ?? ""}"`, `set y2tics`, `set ytics nomirror`);
  }
  const plots = spec.series.map((s, i) => {
    const pt = POINT_TYPES[i % POINT_TYPES.length];
    const axes = s.y2 ? " axes x1y2" : "";
    const dt = s.y2 ? " dt 2" : "";
    return `  "${spec.name}.dat" using ${xcol}:${s.col}${axes} ` +
      `with linespoints lw 2 pt ${pt} ps 1.2${dt} title "${s.title}"`;
  });
  return head.join("\n") + "\nplot \\\n" + plots.join(", \\\n") + "\n";
}

export async function writeGp(dir: string, spec: PlotSpec): Promise<string> {
  await Deno.mkdir(dir, { recursive: true });
  const path = `${dir}/${spec.name}.gp`;
  await Deno.writeTextFile(path, gnuplotScript(spec));
  return path;
}

// ── Rendering (graceful: gnuplot optional) ──────────────────────────────────────

/** True when a `gnuplot` binary is callable on PATH. */
export async function gnuplotAvailable(): Promise<boolean> {
  try {
    const { success } = await new Deno.Command("gnuplot", {
      args: ["--version"],
      stdout: "null",
      stderr: "null",
    }).output();
    return success;
  } catch {
    return false;
  }
}

/**
 * Render every `*.gp` in `dir` to its PNG by running gnuplot with `dir` as cwd (so
 * the scripts' relative `set output`/`<name>.dat` paths resolve inside `out/`).
 * When gnuplot is absent, print where the data + scripts landed and how to render
 * them later — the benchmark never fails over a missing plotting tool.
 */
export async function renderGraphs(dir: string): Promise<void> {
  const gps: string[] = [];
  try {
    for await (const e of Deno.readDir(dir)) {
      if (e.isFile && e.name.endsWith(".gp")) gps.push(e.name);
    }
  } catch {
    // out/ doesn't exist (no data written) — nothing to do.
    return;
  }
  gps.sort();

  if (!(await gnuplotAvailable())) {
    console.log(
      `\ngnuplot not found on PATH — wrote ${gps.length} data/script pair(s) to ${dir}.\n` +
        `Install it and render the paper graphs with:\n` +
        `  sudo apt-get install gnuplot   # (or: brew install gnuplot)\n` +
        `  deno task bench:plot`,
    );
    return;
  }

  for (const gp of gps) {
    const { success, stderr } = await new Deno.Command("gnuplot", {
      args: [gp],
      cwd: dir,
      stdout: "null",
      stderr: "piped",
    }).output();
    if (success) {
      console.log(`  rendered ${gp.replace(/\.gp$/, ".png")}`);
    } else {
      console.error(`  gnuplot failed on ${gp}: ${new TextDecoder().decode(stderr).trim()}`);
    }
  }
  console.log(`\nGraphs written to ${dir}`);
}
