/// <reference lib="deno.ns" />
import { strict as assert } from "node:assert";
import * as XLSX from "xlsx";
import { parseCsvToFields } from "./buildingSerializer.ts";

// The downloadable templates in public/templates/ are generated by
// excel/gen-templates.ts with synthetic data. These tests prove the
// regenerated files still import via parseCsvToFields (same structure the real
// partner templates had), and double as a guard that no real partner data
// leaked into them.

const DIR = "public/templates";
const REAL_PARTNER_STRINGS = [
  "Aurelis",
  "Panattoni",
  "Zufall",
  "LIP Invest",
  "ZP-87461",
  "Adam-von-Trott",
];

function fileOf(name: string): File {
  return new File([Deno.readFileSync(`${DIR}/${name}`)], name);
}

Deno.test("investor template imports three synthetic buildings", async () => {
  const parsed = await parseCsvToFields(fileOf("investor-template.xlsx"), "investor");
  assert.equal(parsed.length, 3);

  const b1 = parsed[0];
  assert.equal(b1.buildingCode, "B-001");
  assert.equal(b1.label, "Musterhausen");
  assert.equal(b1.streetAddress, "Industriestraße 1");
  assert.equal(b1.postalCode, "10115");
  assert.equal(b1.locality, "Berlin");
  assert.equal(b1.yearOfConstruction, "2015");
  // Per-year energy + renewable share attached to years with electricity.
  assert.equal(b1._inv_elec_2024, "505000");
  assert.equal(b1._inv_water_2024, "910");
  assert.equal(b1._inv_renew_2024, "15");
  // Operating costs (Servicelevel section) + certification (per system) import.
  assert.equal(b1._opcost_wasteDisposal, "Mittel");
  assert.equal(b1._opcost_insurance, "All-Risk");
  assert.equal(b1._cert_0_type, "DGNB");
  assert.equal(b1._cert_0_level, "Gold (ab 65%)");
});

Deno.test("BSP template imports three synthetic rows", async () => {
  const parsed = await parseCsvToFields(
    fileOf("bsp-template.xlsx"),
    "benchmark_service_provider",
  );
  assert.equal(parsed.length, 3);

  const b1 = parsed[0];
  assert.equal(b1.companyName, "Beispiel Logistik GmbH");
  assert.equal(b1.label, "Musterhausen");
  assert.equal(b1.streetAddress, "Industriestraße 1");
  assert.equal(b1.postalCode, "10115");
  assert.equal(b1._bsp_elec, "505000");
  assert.equal(b1._bsp_water, "910");
  assert.equal(b1._bsp_year, "2024");
});

Deno.test("Lastgang template imports a synthetic one-day load profile", async () => {
  const parsed = await parseCsvToFields(fileOf("user-lastgang-template.xlsx"), "user");
  assert.equal(parsed.length, 1);
  assert.equal(parsed[0].label, "Beispiel Logistik Lager 1");

  const readings = JSON.parse(parsed[0]._readings_json) as Array<{ valueKwh: string }>;
  assert.equal(readings.length, 96);
  assert.ok(Number(readings[0].valueKwh) >= 0);
});

Deno.test("regenerated templates contain no real partner data", () => {
  for (const name of [
    "investor-template.xlsx",
    "bsp-template.xlsx",
    "user-lastgang-template.xlsx",
  ]) {
    const wb = XLSX.read(Deno.readFileSync(`${DIR}/${name}`), { type: "array", raw: true });
    // Collect every sheet name and every cell value.
    const haystack: string[] = [...wb.SheetNames];
    for (const sn of wb.SheetNames) {
      const ws = wb.Sheets[sn];
      const range = XLSX.utils.decode_range(ws["!ref"] ?? "A1");
      for (let r = range.s.r; r <= range.e.r; r++) {
        for (let c = range.s.c; c <= range.e.c; c++) {
          const cell = ws[XLSX.utils.encode_cell({ r, c })];
          if (cell?.v != null) haystack.push(String(cell.v));
        }
      }
    }
    const blob = haystack.join("\n");
    for (const s of REAL_PARTNER_STRINGS) {
      assert.ok(!blob.includes(s), `${name} still contains "${s}"`);
    }
  }
});
