/**
 * Codegen: parse the three owned `vocab/*.ttl` ontologies and emit
 * `src/services/rdf/vocabLabels.generated.ts` — a flat, IRI-keyed catalog of
 * `rdfs:label` and `rdfs:comment` literals per language tag.
 *
 * Run via `deno task gen:labels`. The vocab files in the repo are the source of
 * truth (see vocab/README.md); the app must NOT fetch the vocab at runtime, so
 * the labels are baked into the bundle here. A freshness test
 * (`vocabLabels.test.ts`) regenerates the maps in memory and asserts they equal
 * the committed file, so the generated module can't fall behind the vocab.
 */

import { Parser } from "n3";

export type Lang = "de" | "en" | "fr";

/** IRI → { lang → literal }. The shape of both emitted maps. */
export type LangMap = Record<string, Partial<Record<Lang, string>>>;

const RDFS_LABEL = "http://www.w3.org/2000/01/rdf-schema#label";
const RDFS_COMMENT = "http://www.w3.org/2000/01/rdf-schema#comment";

/** Namespace IRI → vocab file, relative to repo root. */
export const NS_FILE: Record<string, string> = {
  "https://solid.ti.rw.fau.de/gra/vocab.ttl#": "vocab/vocab.ttl",
  "https://solid.ti.rw.fau.de/gra/building.ttl#": "vocab/building.ttl",
  "https://solid.ti.rw.fau.de/gra/consumption.ttl#": "vocab/consumption.ttl",
};

const isLang = (s: string): s is Lang => s === "de" || s === "en" || s === "fr";

/**
 * Parse one Turtle document and fold its `rdfs:label`/`rdfs:comment` literals
 * into the running label/comment maps. Parsing with the document IRI as base
 * resolves `<#Foo>` to `<namespace>Foo`. Only `de`/`en`/`fr` tags are kept.
 */
export function collectFromTurtle(
  ttl: string,
  baseIRI: string,
  labels: LangMap,
  comments: LangMap,
): void {
  const quads = new Parser({ baseIRI }).parse(ttl);
  for (const q of quads) {
    if (q.object.termType !== "Literal") continue;
    const lang = q.object.language;
    if (!isLang(lang)) continue;
    const target = q.predicate.value === RDFS_LABEL
      ? labels
      : q.predicate.value === RDFS_COMMENT
      ? comments
      : undefined;
    if (!target) continue;
    (target[q.subject.value] ??= {})[lang] = q.object.value;
  }
}

/** Read all owned vocab files and build the combined label + comment maps. */
export function generateMaps(
  repoRoot: string,
): { labels: LangMap; comments: LangMap } {
  const labels: LangMap = {};
  const comments: LangMap = {};
  for (const [ns, file] of Object.entries(NS_FILE)) {
    const ttl = Deno.readTextFileSync(`${repoRoot}/${file}`);
    collectFromTurtle(ttl, ns.slice(0, -1), labels, comments);
  }
  return { labels, comments };
}

/** Render a `LangMap` as a deterministic (key-sorted) TS object literal. */
function serializeMap(map: LangMap): string {
  const iris = Object.keys(map).sort();
  const lines = iris.map((iri) => {
    const byLang = map[iri];
    const inner = (["de", "en", "fr"] as const)
      .filter((l) => byLang[l] !== undefined)
      .map((l) => `${l}: ${JSON.stringify(byLang[l])}`)
      .join(", ");
    return `  ${JSON.stringify(iri)}: { ${inner} },`;
  });
  return `{\n${lines.join("\n")}\n}`;
}

/** Emit the generated module text for the given maps. */
export function renderModule(labels: LangMap, comments: LangMap): string {
  return `// GENERATED by \`deno task gen:labels\` — do not edit
//
// Flat, IRI-keyed catalog of rdfs:label / rdfs:comment literals per language,
// parsed from vocab/*.ttl. Source of truth is the .ttl files; regenerate with
// \`deno task gen:labels\`. A freshness test guards against drift.

export type Lang = "de" | "en" | "fr";

export const VOCAB_LABELS: Record<string, Partial<Record<Lang, string>>> =
  ${serializeMap(labels)};

export const VOCAB_COMMENTS: Record<string, Partial<Record<Lang, string>>> =
  ${serializeMap(comments)};
`;
}

function main(): void {
  // scripts/ is one level under the repo root.
  const repoRoot = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
  const { labels, comments } = generateMaps(repoRoot);
  const out = `${repoRoot}/src/services/rdf/vocabLabels.generated.ts`;
  Deno.writeTextFileSync(out, renderModule(labels, comments));
  const labelCount = Object.keys(labels).length;
  const commentCount = Object.keys(comments).length;
  console.log(
    `Wrote ${out}: ${labelCount} labelled terms, ${commentCount} commented terms.`,
  );
}

if (import.meta.main) main();
