/// <reference lib="deno.ns" />
import { strict as assert } from "node:assert";
import {
  collectFromTurtle,
  type LangMap,
  renderModule,
} from "./genVocabLabels.ts";

const FIXTURE = `
@prefix : <#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

:term rdfs:label "term"@en ; rdfs:label "Begriff"@de ; rdfs:label "terme"@fr ;
    rdfs:comment "a thing"@en ; rdfs:comment "eine Sache"@de .

:partial rdfs:label "partial"@en ; rdfs:label "Teil"@de .

:other rdfs:label "ignored"@es .
`;

const BASE = "https://example.org/v#";

Deno.test("collectFromTurtle keeps all three target langs, drops untargeted ones", () => {
  const labels: LangMap = {};
  const comments: LangMap = {};
  collectFromTurtle(FIXTURE, BASE.slice(0, -1), labels, comments);

  assert.deepEqual(labels[`${BASE}term`], {
    en: "term",
    de: "Begriff",
    fr: "terme",
  });
  // @es is not a supported language → dropped.
  assert.deepEqual(labels[`${BASE}other`], undefined);
  // partial carries only en/de.
  assert.deepEqual(labels[`${BASE}partial`], { en: "partial", de: "Teil" });
});

Deno.test("collectFromTurtle separates labels from comments", () => {
  const labels: LangMap = {};
  const comments: LangMap = {};
  collectFromTurtle(FIXTURE, BASE.slice(0, -1), labels, comments);

  assert.deepEqual(comments[`${BASE}term`], { en: "a thing", de: "eine Sache" });
  // :partial has no comment.
  assert.equal(comments[`${BASE}partial`], undefined);
});

Deno.test("renderModule emits a parseable, key-sorted module with the header", () => {
  const labels: LangMap = {
    "https://z.example/#z": { en: "zee" },
    "https://a.example/#a": { en: "ay", de: "ah" },
  };
  const out = renderModule(labels, {});
  assert.ok(out.startsWith("// GENERATED by `deno task gen:labels` — do not edit"));
  // a sorts before z.
  assert.ok(out.indexOf("a.example") < out.indexOf("z.example"));
  // Lang order within an entry is de, en, fr (fixed serialization order).
  assert.ok(out.includes('"https://a.example/#a": { de: "ah", en: "ay" }'));
});
