// AUTO-GENERATED by `deno task gen:demo-buildings` (scripts/genDemoBuildings.ts)
// from `L.Immo-online-Objektdaten-Auszug Nürnberg_2025-07-01.xlsx` — do not edit by hand.
// Source SHA-256: 519e965a9d3581d38083f76277bf7b70c2389e43071ad3f33f3fe8e29c664c58
//
// 37 real logistics buildings (L.Immo online extract, Nürnberg region) with
// coordinates from the extract and DETERMINISTIC SYNTHETIC energy data — see
// the generator for the synthesis model and the feature-coverage picks
// (series/planned/PV/selfOperated buildings).
import type { DemoSpec } from "./demoSpec.ts";

export const DEMO_BUILDINGS: readonly DemoSpec[] = [
  {
    "fields": {
      "streetAddress": "Daimlerstr. 7",
      "postalCode": "90592",
      "locality": "Schwarzenbruck",
      "region": "Bayern",
      "customer": "B+S GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "30678",
      "buildingCode": "LI-76",
      "yearOfConstruction": "2016",
      "lat": "49.3474297391754",
      "long": "11.2662744225287",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "1168400",
      "_inv_heat_2022": "1774600",
      "_inv_water_2022": "3150",
      "_inv_elec_2023": "1128500",
      "_inv_heat_2023": "1665600",
      "_inv_water_2023": "3040",
      "_inv_elec_2024": "1021200",
      "_inv_heat_2024": "1661500",
      "_inv_water_2024": "2770"
    }
  },
  {
    "fields": {
      "streetAddress": "Am Rettelloh 13",
      "postalCode": "92342",
      "locality": "Freystadt",
      "region": "Bayern",
      "customer": "Hermes Fulfilment Ansbach GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "18923",
      "buildingCode": "LI-3192",
      "yearOfConstruction": "1996",
      "lat": "49.2046041516653",
      "long": "11.3490417764615",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "688000",
      "_inv_heat_2022": "1358900",
      "_inv_water_2022": "1930",
      "_inv_elec_2023": "664700",
      "_inv_heat_2023": "1275600",
      "_inv_water_2023": "1870",
      "_inv_elec_2024": "644000",
      "_inv_heat_2024": "1261200",
      "_inv_water_2024": "1810"
    }
  },
  {
    "fields": {
      "streetAddress": "Rheinstr. 22-24",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Panalpina Welttransport (Deutschland) GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "10127",
      "buildingCode": "LI-3359",
      "yearOfConstruction": "2006",
      "lat": "49.4160054221684",
      "long": "11.0540033445928",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "348100",
      "_inv_heat_2022": "508900",
      "_inv_water_2022": "930",
      "_inv_elec_2023": "326900",
      "_inv_heat_2023": "491800",
      "_inv_water_2023": "870",
      "_inv_elec_2024": "305300",
      "_inv_heat_2024": "472600",
      "_inv_water_2024": "820"
    }
  },
  {
    "fields": {
      "streetAddress": "Koperstr. 10",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Roman Mayer Group",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "20508",
      "buildingCode": "LI-3407",
      "yearOfConstruction": "2011",
      "lat": "49.4052026056665",
      "long": "11.0581772415581",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "758500",
      "_inv_heat_2022": "1479000",
      "_inv_water_2022": "1940",
      "_inv_elec_2023": "756000",
      "_inv_heat_2023": "1428500",
      "_inv_water_2023": "1820",
      "_inv_elec_2024": "708200",
      "_inv_heat_2024": "1304100",
      "_inv_water_2024": "1710"
    }
  },
  {
    "fields": {
      "streetAddress": "Hamburgerstr. 2",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Geis Industrie-Service GmbH",
      "usedAs": "Parcel and courier hub",
      "naceCode": "53",
      "buildingArea": "15334",
      "buildingCode": "LI-3413",
      "yearOfConstruction": "2016",
      "lat": "49.4057891558467",
      "long": "11.052248191413",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "820400",
      "_inv_heat_2022": "738000",
      "_inv_water_2022": "1500",
      "_inv_elec_2023": "792900",
      "_inv_heat_2023": "693000",
      "_inv_water_2023": "1450",
      "_inv_elec_2024": "768500",
      "_inv_heat_2024": "645300",
      "_inv_water_2024": "1400"
    }
  },
  {
    "fields": {
      "streetAddress": "Duisburgerstr. 24",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Geis Industrie-Service GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "15179",
      "buildingCode": "LI-3415",
      "yearOfConstruction": "2021",
      "lat": "49.4049687905628",
      "long": "11.0496297321565",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "557200",
      "_inv_heat_2022": "612700",
      "_inv_water_2022": "1400",
      "_inv_elec_2023": "538300",
      "_inv_heat_2023": "575100",
      "_inv_water_2023": "1350",
      "_inv_elec_2024": "520200",
      "_inv_heat_2024": "570200",
      "_inv_water_2024": "1300"
    }
  },
  {
    "fields": {
      "streetAddress": "Kraftwerkstr. 21",
      "postalCode": "91056",
      "locality": "Erlangen",
      "region": "Bayern",
      "customer": "Faber Castell",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "27723",
      "buildingCode": "LI-3632",
      "yearOfConstruction": "2011",
      "lat": "49.5626328750128",
      "long": "10.9719746161588",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "833800",
      "_inv_heat_2022": "1510000",
      "_inv_water_2022": "2220",
      "_inv_elec_2023": "831000",
      "_inv_heat_2023": "1458700",
      "_inv_water_2023": "2080",
      "_inv_elec_2024": "780700",
      "_inv_heat_2024": "1327200",
      "_inv_water_2024": "1960"
    },
    "selfOperated": true,
    "selfOwned": true
  },
  {
    "fields": {
      "streetAddress": "Koperstr. 3",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Raben Trans European Germany",
      "usedAs": "Freight transport depot",
      "naceCode": "49",
      "buildingArea": "15052",
      "buildingCode": "LI-3951",
      "yearOfConstruction": "2011",
      "lat": "49.401501321752",
      "long": "11.060960346006",
      "geocodePrecision": "Address"
    },
    "energy": "both",
    "annual": {
      "_inv_elec_2022": "432600",
      "_inv_heat_2022": "955600",
      "_inv_water_2022": "1310",
      "_inv_elec_2023": "431400",
      "_inv_heat_2023": "869500",
      "_inv_water_2023": "1230",
      "_inv_elec_2024": "401700",
      "_inv_heat_2024": "838100",
      "_inv_water_2024": "1150"
    },
    "seriesDays": 7,
    "selfOperated": true,
    "selfOwned": true
  },
  {
    "fields": {
      "streetAddress": "Duisburger Str. 101-105",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Multiuser - Duisburger Str.",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "31262",
      "buildingCode": "LI-3956",
      "yearOfConstruction": "2006",
      "lat": "49.3935223968678",
      "long": "11.0474846993486",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "1111300",
      "_inv_heat_2022": "2220900",
      "_inv_water_2022": "3250",
      "_inv_elec_2023": "1073600",
      "_inv_heat_2023": "2084800",
      "_inv_water_2023": "3140",
      "_inv_elec_2024": "1040100",
      "_inv_heat_2024": "2061400",
      "_inv_water_2024": "2860"
    }
  },
  {
    "fields": {
      "streetAddress": "Am Tower 10",
      "postalCode": "90475",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "DHL",
      "usedAs": "Parcel and courier hub",
      "naceCode": "53",
      "buildingArea": "21340",
      "buildingCode": "LI-4095",
      "yearOfConstruction": "2001",
      "lat": "49.3880849341245",
      "long": "11.1815593435211",
      "geocodePrecision": "Address"
    },
    "energy": "both",
    "annual": {
      "_inv_elec_2022": "1056700",
      "_inv_heat_2022": "1289900",
      "_inv_water_2022": "2310",
      "_inv_elec_2023": "991900",
      "_inv_heat_2023": "1246200",
      "_inv_water_2023": "2170",
      "_inv_elec_2024": "980700",
      "_inv_heat_2024": "1200800",
      "_inv_water_2024": "2020"
    },
    "seriesDays": 14,
    "selfOperated": true,
    "selfOwned": true
  },
  {
    "fields": {
      "streetAddress": "Triesdorf Bahnhof 19",
      "postalCode": "91732",
      "locality": "Merkendorf",
      "region": "Bayern",
      "customer": "NBHX",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "14641",
      "buildingCode": "LI-4133",
      "yearOfConstruction": "2001",
      "lat": "49.2035568403652",
      "long": "10.6775312778803",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "569500",
      "_inv_heat_2022": "906600",
      "_inv_water_2022": "1350",
      "_inv_elec_2023": "550400",
      "_inv_heat_2023": "851300",
      "_inv_water_2023": "1300",
      "_inv_elec_2024": "531900",
      "_inv_heat_2024": "794900",
      "_inv_water_2024": "1180"
    }
  },
  {
    "fields": {
      "streetAddress": "Preßburger Str. 4",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "AEG-Electrolux",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "32718",
      "buildingCode": "LI-4178",
      "lat": "49.3887535215327",
      "long": "11.0579084763447",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "1143700",
      "_inv_heat_2022": "2819700",
      "_inv_water_2022": "3140",
      "_inv_elec_2023": "1140400",
      "_inv_heat_2023": "2724100",
      "_inv_water_2023": "2950",
      "_inv_elec_2024": "1065200",
      "_inv_heat_2024": "2617300",
      "_inv_water_2024": "2930"
    }
  },
  {
    "fields": {
      "streetAddress": "Duisburgerstr. 65",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "GAT Logistik GmbH & Co. KG",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "18451",
      "buildingCode": "LI-4179",
      "yearOfConstruction": "2001",
      "lat": "49.3990538762532",
      "long": "11.0489651167916",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "511100",
      "_inv_heat_2022": "1143600",
      "_inv_water_2022": "1510",
      "_inv_elec_2023": "493700",
      "_inv_heat_2023": "1073500",
      "_inv_water_2023": "1460",
      "_inv_elec_2024": "450500",
      "_inv_heat_2024": "1044500",
      "_inv_water_2024": "1330"
    }
  },
  {
    "fields": {
      "streetAddress": "Rotterdamer Str. 32",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Rhenus Logistics",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "13292",
      "buildingCode": "LI-4188",
      "yearOfConstruction": "1996",
      "lat": "49.4003980492176",
      "long": "11.0656848042028",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "418800",
      "_inv_heat_2022": "862900",
      "_inv_water_2022": "1060",
      "_inv_elec_2023": "380900",
      "_inv_heat_2023": "810000",
      "_inv_water_2023": "1030",
      "_inv_elec_2024": "369300",
      "_inv_heat_2024": "801100",
      "_inv_water_2024": "990"
    }
  },
  {
    "fields": {
      "streetAddress": "Koperstr. 2",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Kühne + Nagel (AG & Co.) KG",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "19218",
      "buildingCode": "LI-4202",
      "yearOfConstruction": "2011",
      "lat": "49.4037365099627",
      "long": "11.0585445999185",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "743600",
      "_inv_heat_2022": "1131900",
      "_inv_water_2022": "1570",
      "_inv_elec_2023": "741300",
      "_inv_heat_2023": "1093800",
      "_inv_water_2023": "1470",
      "_inv_elec_2024": "692500",
      "_inv_heat_2024": "1051200",
      "_inv_water_2024": "1460"
    }
  },
  {
    "fields": {
      "streetAddress": "Aischweg 2",
      "postalCode": "90768",
      "locality": "Fürth",
      "region": "Bayern",
      "customer": "NORDFROST GmbH & Co. KG",
      "usedAs": "Cold storage",
      "naceCode": "52",
      "buildingArea": "10307",
      "buildingCode": "LI-4212",
      "yearOfConstruction": "2011",
      "lat": "49.4984812082861",
      "long": "10.9450757331269",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "631400",
      "_inv_heat_2022": "260200",
      "_inv_water_2022": "1150",
      "_inv_elec_2023": "609900",
      "_inv_heat_2023": "244300",
      "_inv_water_2023": "1110",
      "_inv_elec_2024": "555000",
      "_inv_heat_2024": "242200",
      "_inv_water_2024": "1010"
    }
  },
  {
    "fields": {
      "streetAddress": "Sieboldstr. 20",
      "postalCode": "90411",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Schwarz Logistik GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "12127",
      "buildingCode": "LI-4351",
      "yearOfConstruction": "2006",
      "lat": "49.4792633292889",
      "long": "11.1256567624333",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "421800",
      "_inv_heat_2022": "743300",
      "_inv_water_2022": "1250",
      "_inv_elec_2023": "407600",
      "_inv_heat_2023": "698000",
      "_inv_water_2023": "1210",
      "_inv_elec_2024": "392800",
      "_inv_heat_2024": "653600",
      "_inv_water_2024": "1090"
    }
  },
  {
    "fields": {
      "streetAddress": "Wittekindstr. 28",
      "postalCode": "90431",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Christian Rak Transporthilfen",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "19971",
      "buildingCode": "LI-4700",
      "yearOfConstruction": "2001",
      "lat": "49.4602541551169",
      "long": "11.0137857734159",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "660300",
      "_inv_heat_2022": "1646500",
      "_inv_water_2022": "1780",
      "_inv_elec_2023": "638100",
      "_inv_heat_2023": "1546100",
      "_inv_water_2023": "1720",
      "_inv_elec_2024": "616700",
      "_inv_heat_2024": "1443700",
      "_inv_water_2024": "1650"
    }
  },
  {
    "fields": {
      "streetAddress": "Graf-Zeppelin-Str. 11",
      "postalCode": "91056",
      "locality": "Erlangen",
      "region": "Bayern",
      "customer": "Ludwig Peetz GmbH & Co. KG",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "27128",
      "buildingCode": "LI-4704",
      "yearOfConstruction": "2001",
      "lat": "49.5614274924795",
      "long": "10.9679677147887",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "1040100",
      "_inv_heat_2022": "2222200",
      "_inv_water_2022": "2840",
      "_inv_elec_2023": "946600",
      "_inv_heat_2023": "2085900",
      "_inv_water_2023": "2740",
      "_inv_elec_2024": "909700",
      "_inv_heat_2024": "2080200",
      "_inv_water_2024": "2500"
    }
  },
  {
    "fields": {
      "streetAddress": "Hamburgerstr. 24",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Geis Eurocargo GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "10051",
      "buildingCode": "LI-4736",
      "yearOfConstruction": "2006",
      "lat": "49.4026575087774",
      "long": "11.0523393464605",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "335800",
      "_inv_heat_2022": "607300",
      "_inv_water_2022": "770",
      "_inv_elec_2023": "334700",
      "_inv_heat_2023": "586600",
      "_inv_water_2023": "770",
      "_inv_elec_2024": "312700",
      "_inv_heat_2024": "530800",
      "_inv_water_2024": "720"
    }
  },
  {
    "fields": {
      "streetAddress": "Koblenzer Str. 13",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "UPS",
      "usedAs": "Parcel and courier hub",
      "naceCode": "53",
      "buildingArea": "16061",
      "buildingCode": "LI-4738",
      "yearOfConstruction": "2001",
      "lat": "49.3901478394181",
      "long": "11.0459227201356",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "709400",
      "_inv_heat_2022": "1290200",
      "_inv_water_2022": "1820",
      "_inv_elec_2023": "707000",
      "_inv_heat_2023": "1246600",
      "_inv_water_2023": "1710",
      "_inv_elec_2024": "658600",
      "_inv_heat_2024": "1201300",
      "_inv_water_2024": "1690"
    }
  },
  {
    "fields": {
      "streetAddress": "Duisburger Str. 4",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Multiuser Greenfield Logistikpark - 2.BA",
      "usedAs": "Logistics park",
      "naceCode": "64",
      "buildingArea": "21341",
      "buildingCode": "LI-4745",
      "yearOfConstruction": "2016",
      "lat": "49.4048658843517",
      "long": "11.060736512694",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "774800",
      "_inv_heat_2022": "979700",
      "_inv_water_2022": "1720",
      "_inv_elec_2023": "772500",
      "_inv_heat_2023": "946500",
      "_inv_water_2023": "1610",
      "_inv_elec_2024": "719500",
      "_inv_heat_2024": "911800",
      "_inv_water_2024": "1590"
    }
  },
  {
    "fields": {
      "streetAddress": "Thomas-Dachser-Str. 1",
      "postalCode": "90475",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "ELSEN Holding GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "16432",
      "buildingCode": "LI-4753",
      "yearOfConstruction": "2006",
      "lat": "49.3854572153699",
      "long": "11.1734142606287",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "624800",
      "_inv_heat_2022": "1112600",
      "_inv_water_2022": "1840",
      "_inv_elec_2023": "603600",
      "_inv_heat_2023": "1109400",
      "_inv_water_2023": "1780",
      "_inv_elec_2024": "579900",
      "_inv_heat_2024": "1042100",
      "_inv_water_2024": "1720"
    }
  },
  {
    "fields": {
      "streetAddress": "Am hohen Bühl 01-05",
      "postalCode": "90475",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "TNT Express GmbH",
      "usedAs": "Parcel and courier hub",
      "naceCode": "53",
      "buildingArea": "11306",
      "buildingCode": "LI-4754",
      "yearOfConstruction": "2001",
      "lat": "49.3870351676752",
      "long": "11.1730929579053",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "612800",
      "_inv_heat_2022": "887800",
      "_inv_water_2022": "1060",
      "_inv_elec_2023": "575200",
      "_inv_heat_2023": "857700",
      "_inv_water_2023": "1060",
      "_inv_elec_2024": "573700",
      "_inv_heat_2024": "828700",
      "_inv_water_2024": "990"
    }
  },
  {
    "fields": {
      "streetAddress": "Gildestr. 17",
      "postalCode": "91154",
      "locality": "Roth",
      "region": "Bayern",
      "customer": "FIEGE Logistik",
      "usedAs": "Freight transport depot",
      "naceCode": "49",
      "buildingArea": "13721",
      "buildingCode": "LI-4797",
      "yearOfConstruction": "2001",
      "lat": "49.2502523244253",
      "long": "11.1135589804399",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "388700",
      "_inv_heat_2022": "811700",
      "_inv_water_2022": "1170",
      "_inv_elec_2023": "375600",
      "_inv_heat_2023": "809000",
      "_inv_water_2023": "1070",
      "_inv_elec_2024": "361000",
      "_inv_heat_2024": "760000",
      "_inv_water_2024": "1030"
    }
  },
  {
    "fields": {
      "streetAddress": "Kirchhoffstr. 4",
      "postalCode": "90431",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Systemtrans stl GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "20133",
      "buildingCode": "LI-4822",
      "yearOfConstruction": "2006",
      "lat": "49.4313306355962",
      "long": "11.0312505408583",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "609000",
      "_inv_heat_2022": "1250700",
      "_inv_water_2022": "1670",
      "_inv_elec_2023": "607000",
      "_inv_heat_2023": "1208000",
      "_inv_water_2023": "1560",
      "_inv_elec_2024": "567000",
      "_inv_heat_2024": "1093400",
      "_inv_water_2024": "1460"
    }
  },
  {
    "fields": {
      "streetAddress": "Hofstettener Hauptstr. 5",
      "postalCode": "91161",
      "locality": "Hilpoltstein",
      "region": "Bayern",
      "customer": "Greiner Logistik Lagerung",
      "usedAs": "Freight transport depot",
      "naceCode": "49",
      "buildingArea": "13357",
      "buildingCode": "LI-4980",
      "yearOfConstruction": "2006",
      "lat": "49.1817948109771",
      "long": "11.1755187005801",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "324100",
      "_inv_heat_2022": "738600",
      "_inv_water_2022": "1250",
      "_inv_elec_2023": "313100",
      "_inv_heat_2023": "693600",
      "_inv_water_2023": "1210",
      "_inv_elec_2024": "303400",
      "_inv_heat_2024": "645700",
      "_inv_water_2024": "1170"
    }
  },
  {
    "fields": {
      "streetAddress": "Poststr. 2",
      "postalCode": "90471",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Briefzentrum 90",
      "usedAs": "Parcel and courier hub",
      "naceCode": "53",
      "buildingArea": "34200",
      "buildingCode": "LI-5038",
      "yearOfConstruction": "2001",
      "lat": "49.4195346824459",
      "long": "11.1361688664465",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "1953300",
      "_inv_heat_2022": "2760100",
      "_inv_water_2022": "3570",
      "_inv_elec_2023": "1834400",
      "_inv_heat_2023": "2666400",
      "_inv_water_2023": "3350",
      "_inv_elec_2024": "1718200",
      "_inv_heat_2024": "2583300",
      "_inv_water_2024": "3140"
    }
  },
  {
    "fields": {
      "streetAddress": "Hamburgerstr. 99",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Amm GmbH & Co. KG",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "12868",
      "buildingCode": "LI-5060",
      "yearOfConstruction": "2001",
      "lat": "49.3898271097757",
      "long": "11.0508896497551",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "378100",
      "_inv_heat_2022": "828100",
      "_inv_water_2022": "1110",
      "_inv_elec_2023": "365400",
      "_inv_heat_2023": "777500",
      "_inv_water_2023": "1010",
      "_inv_elec_2024": "354200",
      "_inv_heat_2024": "723700",
      "_inv_water_2024": "980"
    }
  },
  {
    "fields": {
      "streetAddress": "Bremerstr. 90",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "DB Schenker",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "11554",
      "buildingCode": "LI-5062",
      "yearOfConstruction": "2011",
      "lat": "49.3992744956202",
      "long": "11.0600145091982",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "311200",
      "_inv_heat_2022": "770800",
      "_inv_water_2022": "1080",
      "_inv_elec_2023": "300700",
      "_inv_heat_2023": "723600",
      "_inv_water_2023": "1040",
      "_inv_elec_2024": "289000",
      "_inv_heat_2024": "679500",
      "_inv_water_2024": "950"
    }
  },
  {
    "fields": {
      "streetAddress": "Bremer Str. 152b",
      "postalCode": "90451",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "DB Schenker",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "38557",
      "buildingCode": "LI-5069",
      "yearOfConstruction": "2011",
      "lat": "49.3960110803664",
      "long": "11.0567256668848",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "1152900",
      "_inv_heat_2022": "2282000",
      "_inv_water_2022": "3810",
      "_inv_elec_2023": "1082100",
      "_inv_heat_2023": "2205000",
      "_inv_water_2023": "3580",
      "_inv_elec_2024": "1073400",
      "_inv_heat_2024": "2118800",
      "_inv_water_2024": "3550"
    }
  },
  {
    "fields": {
      "streetAddress": "Steinauer Weg 7",
      "postalCode": "91589",
      "locality": "Aurach",
      "region": "Bayern",
      "customer": "Loxxess AG",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "33464",
      "buildingCode": "LI-14235",
      "yearOfConstruction": "2021",
      "lat": "49.2530209995962",
      "long": "10.422785000006",
      "geocodePrecision": "Address",
      "_pv_capacityKW": "1200",
      "_pv_commissioningYear": "2021"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "897800",
      "_inv_heat_2022": "1949700",
      "_inv_water_2022": "3520",
      "_inv_elec_2023": "867500",
      "_inv_heat_2023": "1830100",
      "_inv_water_2023": "3400",
      "_inv_elec_2024": "840700",
      "_inv_heat_2024": "1809700",
      "_inv_water_2024": "3280",
      "_inv_gen_2022": "1139500",
      "_inv_gen_2023": "1146900",
      "_inv_gen_2024": "1156500"
    }
  },
  {
    "fields": {
      "streetAddress": "Steinauer Weg 7",
      "postalCode": "91074",
      "locality": "Aurach",
      "region": "Bayern",
      "customer": "Multiuser Logistikpark Aurach",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "33800",
      "buildingCode": "LI-14973",
      "yearOfConstruction": "2021",
      "lat": "49.2544599976844",
      "long": "10.4274260000343",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "1271600",
      "_inv_heat_2022": "1736100",
      "_inv_water_2022": "3100",
      "_inv_elec_2023": "1267500",
      "_inv_heat_2023": "1676900",
      "_inv_water_2023": "2910",
      "_inv_elec_2024": "1190700",
      "_inv_heat_2024": "1526300",
      "_inv_water_2024": "2730"
    }
  },
  {
    "fields": {
      "streetAddress": "Kurt Nagel Platz 1",
      "postalCode": "90475",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Nagel Group",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "13607",
      "buildingCode": "LI-15610",
      "yearOfConstruction": "2006",
      "lat": "49.3864644548522",
      "long": "11.1825949153234",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "482800",
      "_inv_heat_2022": "746600",
      "_inv_water_2022": "1260",
      "_inv_elec_2023": "466600",
      "_inv_heat_2023": "701100",
      "_inv_water_2023": "1220",
      "_inv_elec_2024": "452200",
      "_inv_heat_2024": "652800",
      "_inv_water_2024": "1180"
    }
  },
  {
    "fields": {
      "streetAddress": "Kirchhoffstr. 5",
      "postalCode": "90431",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "DHL Solutions GmbH",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "27291",
      "buildingCode": "LI-15611",
      "yearOfConstruction": "2001",
      "lat": "49.4306829998521",
      "long": "11.0324781067244",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "824500",
      "_inv_heat_2022": "2135900",
      "_inv_water_2022": "2740",
      "_inv_elec_2023": "773900",
      "_inv_heat_2023": "2064100",
      "_inv_water_2023": "2570",
      "_inv_elec_2024": "767500",
      "_inv_heat_2024": "1983600",
      "_inv_water_2024": "2370"
    }
  },
  {
    "fields": {
      "streetAddress": "Thomas-Dachser-Str. 4",
      "postalCode": "90475",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Dachser Group SE & Co. KG",
      "usedAs": "Logistics warehouse",
      "naceCode": "52",
      "buildingArea": "34438",
      "buildingCode": "LI-16074",
      "yearOfConstruction": "2006",
      "lat": "49.3867542532701",
      "long": "11.1660961907785",
      "geocodePrecision": "Address",
      "leaseType": "Triple net",
      "tenancyType": "SingleTenant",
      "shiftRegime": "TwoShift",
      "indoorTemperatureClass": "MaxEighteenDegrees",
      "numberOfLoadingDocks": "30",
      "_cert_0_type": "DGNB",
      "_cert_0_level": "Gold",
      "_cert_0_scope": "Existing building",
      "_opcost_propertyManagement": "Medium",
      "_opcost_operationInspectionAndMaintenance": "High",
      "_gasboiler_present": "true",
      "_gasboiler_thermalCapacityKW": "900",
      "_gasboiler_commissioningYear": "2006",
      "_heatpump_present": "true",
      "_heatpump_thermalCapacityKW": "250",
      "_heatpump_commissioningYear": "2019"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "1327800",
      "_inv_heat_2022": "2474600",
      "_inv_water_2022": "2870",
      "_inv_elec_2023": "1246400",
      "_inv_heat_2023": "2252100",
      "_inv_water_2023": "2860",
      "_inv_elec_2024": "1236000",
      "_inv_heat_2024": "2164400",
      "_inv_water_2024": "2670"
    },
    "selfOperated": true,
    "planned": {
      "year": 2024,
      "metrics": {
        "electricityConsumption": 1174200,
        "heatConsumption": 2056200,
        "waterConsumption": 2540
      }
    }
  },
  {
    "fields": {
      "streetAddress": "Kurt-Nagel-Platz 1",
      "postalCode": "90475",
      "locality": "Nürnberg",
      "region": "Bayern",
      "customer": "Nagel Group",
      "usedAs": "Freight transport depot",
      "naceCode": "49",
      "buildingArea": "10500",
      "buildingCode": "LI-16167",
      "yearOfConstruction": "2021",
      "lat": "49.3861211538088",
      "long": "11.1843386481359",
      "geocodePrecision": "Address"
    },
    "energy": "annual",
    "annual": {
      "_inv_elec_2022": "335200",
      "_inv_heat_2022": "451100",
      "_inv_water_2022": "830",
      "_inv_elec_2023": "323900",
      "_inv_heat_2023": "423500",
      "_inv_water_2023": "750",
      "_inv_elec_2024": "312200",
      "_inv_heat_2024": "421000",
      "_inv_water_2024": "720"
    }
  }
];

/**
 * Curated subset for the browser test lanes (`VITE_DEMO_SEED=core`): the
 * flagship (planned/Soll pair), the PV/generation building, both series
 * buildings, the cold store (locality spread: Fürth) and one plain-annual
 * building — every shape the e2e specs assert on, at a seed cost close to the
 * old 4-building set. The full set stays covered by the unit seed tests and
 * the headless `seed-demos` task.
 */
const CORE_CODES = new Set(["LI-16074","LI-14235","LI-4095","LI-3951","LI-4212","LI-16167"]);
export const DEMO_BUILDINGS_CORE: readonly DemoSpec[] = DEMO_BUILDINGS.filter(
  (b) => CORE_CODES.has(b.fields.buildingCode),
);
