name: scp to paul
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: install && build  
        run: deno install && deno task build
      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
      - name: download build files
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./dist/"
          target: "./public_html/testing/granergize/"
